version: '3.9'

services:
  server:
    container_name: server
    build: .
    env_file: .env.dev
    restart: unless-stopped
    ports:
      - "8080:3000"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - TZ=Europe/Moscow
    restart: always
    ports:
      - '5432:5432'
    networks:
        - network
    #    volumes:
    #      - ./pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always
    ports:
      - '5555:80'
    networks:
      - network
    depends_on:
      - postgres

networks:
  network:
    name: network
    attachable: true
    driver: bridge
