version: '3.9'

services:
  server:
    container_name: server
    build: .
    env_file: .env.dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - network
    extra_hosts:
      - "localhost:127.0.0.1"

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - TZ=Europe/Moscow
    #    volumes:
    #      - ./pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - '5433:5432'
    networks:
      - network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always
    ports:
      - '5555:80'
    networks:
      - network
    depends_on:
      - postgres

networks:
  network:
    name: network
    attachable: true
    driver: bridge
